### PR TITLE
Passing proxy config setting to octo CLI

### LINKED ISSUE #116: Request to download Octo client does not support a proxy
The `RestClient` used to contact https://g.octopushq.com/LatestTools does not have a way to be configured with a proxy.

### PR DESCRIPTION
**Pull request by johnsimons**
Ensure we pass the proxy configuration set at the agent to the `octo` CLI and the REST call we do to check for latest.

Fixes #116

### CODE REVIEW

**Review by jbristowe — COMMENTED** [review]
Why not preserve `includeArguments` as-is? Why refactor the function at all? Do we want all versions to support proxy arguments? I’m not sure if previous versions of Octopus CLI support it. 🤷‍♂️

**Comment by johnsimons** [comment]
> Do we want all versions to support proxy arguments? I’m not sure if previous versions of Octopus CLI support it.

@jbristowe I think so, it was added in v6.6.0 (7 May 2019)

**Comment by johnsimons** [comment]
> Why not preserve includeArguments as-is? Why refactor the function at all?
Me being lazy and piggy backing on it, do you think we should do it differently?

**Review by slewis74 — APPROVED** [review]
LGTM

**Comment by ValdisThomann** [comment]
> Yes eventually we found the bypass file documentation and added our proxy server to it. Our challenge was in that we didn't make any network changes and suddenly a bunch of builds started breaking in our automated process. So it required us to go back review for any environmental / tooling changes and back-track those to try and find the issue. 

We had the exact same experience

**Comment by johnsimons** [comment]
@ValdisThomann @tdaniels-iowa thanks heaps for the suggestion on improving the logging, I have https://github.com/OctopusDeploy/OctoTFS/pull/202 to fix this.

**Pull request merged**
