### PR TITLE
Dont convert Build.BuildNumber to Number

### PR DESCRIPTION
**Pull request by RobertKozak**
Since Build.BuildNumber might be using SemVer 2.0.0 it will contain more than a number. Currently because of the Number convert it will output as #NaN

### CODE REVIEW

**Comment by antmeehan** [comment]
Nice work @RobertKozak. I was about to open the exact same PR!

**Comment by antmeehan** [comment]
@RobertKozak I think your second commit (merge master) has reverted your changes?

**Comment by RobertKozak** [comment]
> @RobertKozak I think your second commit (merge master) has reverted your changes?

I don't think so. These are the two lines affected:
       buildNumber: Number(process.env["BUILD_BUILDNUMBER"]),
        buildId: Number(process.env["BUILD_BUILDID"]),

> @RobertKozak I think your second commit (merge master) has reverted your changes?

Yeah you are right. I must have messed up the merge. Its literally two lines of code change. Since you were going to open a PR do you want to take care of it? I haven't been keeping up to date with this.

**Comment by antmeehan** [comment]
@RobertKozak I've created https://github.com/OctopusDeploy/OctoTFS/pull/132 now. Thanks.

**Comment by michaelnoonan** [comment]
Thanks! Let's close this PR in lieu of #132.

**Pull request closed without merging**
